#!/usr/bin/env bash

ROOT=$(dirname $(readlink -f $(which "$0")))

source $ROOT/check-requirements.sh

! checkRequirements "fzf";

folder=$(find $PWD -mindepth 1 -maxdepth 5 -type d | fzf)
cd $folder
