#!/usr/bin/env bash

FILE_DIR=$(dirname $(readlink -f $(which "$0")))

source $FILE_DIR/check-requirements.sh

! checkRequirements "fzf";

folder=$(find $PWD -mindepth 1 -maxdepth 5 -type d | fzf)
cd $folder
