#!/usr/bin/env bash

FILE_DIR=$(dirname $(readlink -f $(which "$0")))

source $FILE_DIR/check-requirements.sh

! checkRequirements "docker";

source $FILE_DIR/print.sh

info "Stopping containers"
if [ "`docker ps -q`" ]; then
  docker stop `docker ps -q`
fi

info "Removing containers"
if [ "`docker ps -aq`" ]; then
  docker rm `docker ps -aq`
fi

info "Removing volumes"
if [ "`docker volume ls -q`" ]; then
  docker volume rm `docker volume ls -q`
fi

info "Removing networks"
docker network rm `docker network ls -q`

