#!/usr/bin/env bash

FILE_DIR=$(dirname $(readlink -f $(which "$0")))

source $FILE_DIR/print.sh
source $FILE_DIR/docker-prune
source $FILE_DIR/check-requirements.sh

! checkRequirements "docker";

echo `info "Removing images"`
if [ "`docker image ls -aq`" ]; then
  docker rmi -f `docker image ls -aq`;
fi
