#!/usr/bin/env bash

ROOT=$(dirname $(readlink -f $(which "$0")))

source $ROOT/check-requirements.sh

! checkRequirements "docker";

source $ROOT/print.sh

echo `info "Stopping containers"`
if [ "`docker ps -aq`" ]; then
  docker rm `docker ps -aq`
fi

echo `info "Removing containers"`
if [ "`docker ps -aq`" ]; then
  docker rm `docker ps -aq`
fi

echo `info "Removing volumes"`
if [ "`docker volume ls -q`" ]; then
  docker volume rm `docker volume ls -q`
fi

echo `info "Removing networks"`
docker network rm `docker network ls -q`

