#!/usr/bin/env bash

ROOT=$(dirname $(readlink -f $(which "$0")))

source $ROOT/helpers/print.sh

source $ROOT/docker-prune

echo `info "Removing images"`
if [ "`docker image ls -aq`" ]; then
  docker rmi -f `docker image ls -aq`;
fi
