#!/usr/bin/env bash

FILE_DIR=$(dirname $(readlink -f $(which "$0")))

source $FILE_DIR/check-requirements.sh

! checkRequirements "kubectl";


kubectl get pods "$@" -o jsonpath="{.items[*].spec.containers[*].image}" | \
  tr -s '[[:space:]]' '\n' |\
  sort |\
  uniq -c
