#!/usr/bin/env bash

function details() {
  hr '─'

  echo "Google Cloud Account"
  echo "--------------------"
  gcloud config configurations list | grep True | awk '{print "  Name:\t\t"$1"\n  Account:\t"$2"\n  Project:\t"$3}' | sed -e 's/[^_]*_[^_]*_[^_]*_//'

  printf "  GKE Cluster:\t`kubectl config current-context`\n"

  hr '─'
}

details | grep --color=auto -E "^|production|staging|assurance|development|test"

