#!/usr/bin/env bash

ROOT=$(dirname $(readlink -f $(which "$0")))

source $ROOT/check-requirements.sh

! checkRequirements "tmux";

if [ -z "${TMUX}" ]; then
	echo "You are not inside a tmux session"
else
	tmux select-window -t ${1:-1}
fi
